name: Auto create PR for feature branches

on:
  push:
    branches:
      - "feature.**"

permissions:
  contents: read
  pull-requests: write

jobs:
  create-pr-develop:
    name: Create PR to develop
    # Not run when branch is newly created
    if: ${{ github.event.created == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Create PR if not exist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: ./.github/workflows/create-pr
        with:
          base: develop
          head: ${{ github.ref_name }}
          pr_template_file: .github/PULL_REQUEST_TEMPLATE.md
          is_draft: yes
          labels: '["auto-pr", "develop"]'
          prettify_title: yes

  create-pr-staging:
    name: Create PR to staging
    # Not run when branch is newly created
    if: ${{ github.event.created == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Create PR if not exist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: ./.github/workflows/create-pr
        with:
          base: staging
          head: ${{ github.ref_name }}
          pr_template_file: .github/PULL_REQUEST_TEMPLATE.md
          is_draft: yes
          labels: '["auto-pr", "staging"]'
          prettify_title: yes

  create-pr-master:
    name: Create PR to master
    # Not run when branch is newly created
    if: ${{ github.event.created == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Create PR if not exist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: ./.github/workflows/create-pr
        with:
          base: master
          head: ${{ github.ref_name }}
          pr_template_file: .github/PULL_REQUEST_TEMPLATE.md
          is_draft: yes
          labels: '["auto-pr", "master"]'
          prettify_title: yes
